### ISSUE TITLE
Feedbacks that will not be addressed

### ISSUE THREAD

**Issue by korayt** [UBC-MDS/eda_mds#55]

**Comment by paolocodina** [comment]
Do we need to do this: Add the jupyter notebook package in the pyproject.toml to run example notebook

**Comment by nicolebid** [comment]
From my understanding from the lab, it is not required since the intention of the `example.ipynb` is to render on readthedocs so the users will view it there.

**Comment by srfrew** [comment]
I agree that we don't quite need the jl package. As @nicolebid said one can refer to readthedocs

**Comment by srfrew** [comment]
Another feedback that will not be addressed is the note to include error behaviour in the example vignette. 

This was chosen to not be included since the vignette is intended to provide example useage, and requirements for the functions are clearly stated. It is not intended to be a troubleshooting document! We appreciate the note to include it, but found that it may distract from the overall goal of the example

**Comment by nicolebid** [comment]
Feedback not Addressed: 
 - describe_outliers function's output is not rendering properly (on readthedocs, the table overflows and needs horizontal scroll)
 
I searched and asked around to try and resolve this, but could only find solutions for md files not ipynb. There was a suggestion to subset the columns so there are less to output. but the purpose of this code chunk was to show all the columns it could display in the entire dataset. I feel it would be more confusing to the reader had we then subset the columns.

**Comment by paolocodina** [comment]
We were able to improve coverage but not to get 100% coverage.

**Comment by srfrew** [comment]
Code Coverage to 100%: Some admin files (__init__, continue statements) are showing up as not being covered with codecov, despite them being run in pytest. Coverage was improved significantly
